#!/usr/bin/env python3
"""补充 ai-coding-workflow 到 20 chunks"""
import json

with open('data/lessons/ai-coding-workflow.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_ids = {c['id'] for c in data['chunks']}
print(f"Existing chunks: {len(data['chunks'])}")

new_chunks = [
    {"id": "ai-coding-workflow-006", "chunk": "acceptance criterion", "meaning_cn": "验收标准", "collocations": ["define acceptance criteria", "meet the acceptance criterion"], "sentence": "Each task should have a testable acceptance criterion.", "sentence_cn": "每个任务都应该有可测试的验收标准。", "exam_sentence": "Setting clear criteria helps teams evaluate whether goals have been achieved.", "audio": "/audio/ai-coding-workflow/chunk-006.mp3", "rewrite_prompt_cn": "每个任务都应该有可测试的验收标准。", "retelling_prompt": "Why are acceptance criteria important in software development?", "tags": ["workflow", "quality"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-007", "chunk": "recovery path", "meaning_cn": "恢复路径", "collocations": ["a safe recovery path", "provide a recovery path"], "sentence": "Every deployment should include a safe recovery path.", "sentence_cn": "每次部署都应该包含一个安全的恢复路径。", "exam_sentence": "A good plan always includes a recovery path in case things go wrong.", "audio": "/audio/ai-coding-workflow/chunk-007.mp3", "rewrite_prompt_cn": "每次部署都应该包含一个安全的恢复路径。", "retelling_prompt": "What is a recovery path and why does it matter?", "tags": ["software", "risk"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-008", "chunk": "engineering judgment", "meaning_cn": "工程判断力", "collocations": ["require engineering judgment", "exercise engineering judgment"], "sentence": "AI does not remove the need for engineering judgment.", "sentence_cn": "AI并不能取代工程判断。", "audio": "/audio/ai-coding-workflow/chunk-008.mp3", "rewrite_prompt_cn": "AI并不能取代工程判断。", "retelling_prompt": "Why is engineering judgment still important despite AI?", "tags": ["AI", "engineering"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-009", "chunk": "security risks", "meaning_cn": "安全风险", "collocations": ["reduce security risks", "identify security risks", "security risk assessment"], "sentence": "Developers still need to reduce security risks in AI-generated code.", "sentence_cn": "开发者仍然需要降低AI生成代码中的安全风险。", "exam_sentence": "As technology advances, new security risks emerge that require careful attention.", "audio": "/audio/ai-coding-workflow/chunk-009.mp3", "rewrite_prompt_cn": "开发者仍然需要降低AI生成代码中的安全风险。", "retelling_prompt": "How should developers handle security risks in AI coding?", "tags": ["software", "risk"], "exam_tags": ["IELTS", "TOEFL", "PETS", "Tech English"]},
    {"id": "ai-coding-workflow-010", "chunk": "edge cases", "meaning_cn": "边界情况；边缘情况", "collocations": ["test edge cases", "handle edge cases", "cover edge cases"], "sentence": "Developers still need to test edge cases that AI might miss.", "sentence_cn": "开发者仍然需要测试AI可能遗漏的边界情况。", "exam_sentence": "Thorough preparation means considering not only common situations but also edge cases.", "audio": "/audio/ai-coding-workflow/chunk-010.mp3", "rewrite_prompt_cn": "开发者仍然需要测试AI可能遗漏的边界情况。", "retelling_prompt": "What are edge cases and why should developers test them?", "tags": ["testing", "quality"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-011", "chunk": "test coverage", "meaning_cn": "测试覆盖率", "collocations": ["improve test coverage", "test coverage report", "maintain high test coverage"], "sentence": "Teams should maintain high test coverage to catch bugs early.", "sentence_cn": "团队应该保持高测试覆盖率以尽早发现bug。", "exam_sentence": "Measuring performance requires clear indicators, much like how test coverage measures code quality.", "audio": "/audio/ai-coding-workflow/chunk-011.mp3", "rewrite_prompt_cn": "团队应该保持高测试覆盖率以尽早发现bug。", "retelling_prompt": "Why is test coverage important?", "tags": ["testing", "quality"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-012", "chunk": "code review", "meaning_cn": "代码审查", "collocations": ["go through code review", "code review process", "code review bottleneck"], "sentence": "All changes should go through code review before deployment.", "sentence_cn": "所有修改在部署前都应该经过代码审查。", "exam_sentence": "Peer review is valuable not only in academic research but also in professional practice.", "audio": "/audio/ai-coding-workflow/chunk-012.mp3", "rewrite_prompt_cn": "所有修改在部署前都应该经过代码审查。", "retelling_prompt": "Explain the purpose of code review.", "tags": ["review", "workflow"], "exam_tags": ["IELTS", "TOEFL", "PETS", "Tech English"]},
    {"id": "ai-coding-workflow-013", "chunk": "small and reviewable", "meaning_cn": "小而可审查的", "collocations": ["keep changes small and reviewable"], "sentence": "A useful workflow should keep changes small and reviewable.", "sentence_cn": "一个有用的工作流应该让修改保持小而可审查。", "audio": "/audio/ai-coding-workflow/chunk-013.mp3", "rewrite_prompt_cn": "一个有用的工作流应该让修改保持小而可审查。", "retelling_prompt": "Why should changes be kept small?", "tags": ["workflow", "review"], "exam_tags": ["IELTS", "Tech English"]},
    {"id": "ai-coding-workflow-014", "chunk": "deployment pipeline", "meaning_cn": "部署流水线", "collocations": ["set up a deployment pipeline", "deployment pipeline should support"], "sentence": "The deployment pipeline should support rollback if the new version fails.", "sentence_cn": "部署流水线应该在新版本失败时支持回滚。", "exam_sentence": "Streamlining processes can significantly improve efficiency in any organization.", "audio": "/audio/ai-coding-workflow/chunk-014.mp3", "rewrite_prompt_cn": "部署流水线应该在新版本失败时支持回滚。", "retelling_prompt": "What does a deployment pipeline do?", "tags": ["software", "workflow"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-015", "chunk": "verify the result", "meaning_cn": "验证结果", "collocations": ["verify the result", "carefully verify the output"], "sentence": "Developers still need to verify the result before pushing to production.", "sentence_cn": "开发者仍然需要在推送到生产环境之前验证结果。", "audio": "/audio/ai-coding-workflow/chunk-015.mp3", "rewrite_prompt_cn": "开发者仍然需要在推送到生产环境之前验证结果。", "retelling_prompt": "Why should developers verify AI-generated results?", "tags": ["AI", "quality"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-016", "chunk": "improve productivity", "meaning_cn": "提高生产力", "collocations": ["improve productivity", "boost productivity", "productivity gains"], "sentence": "AI can improve productivity, but it does not remove the need for quality.", "sentence_cn": "AI可以提高生产力，但不能消除对质量的需求。", "audio": "/audio/ai-coding-workflow/chunk-016.mp3", "rewrite_prompt_cn": "AI可以提高生产力，但不能消除对质量的需求。", "retelling_prompt": "How does AI affect productivity in software development?", "tags": ["AI", "workflow"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-017", "chunk": "production environment", "meaning_cn": "生产环境", "collocations": ["deploy to production", "production environment", "production-ready"], "sentence": "No code should reach production without proper testing and review.", "sentence_cn": "没有经过适当测试和审查的代码不应到达生产环境。", "audio": "/audio/ai-coding-workflow/chunk-017.mp3", "rewrite_prompt_cn": "没有经过适当测试和审查的代码不应到达生产环境。", "retelling_prompt": "What safeguards exist before code reaches production?", "tags": ["software", "deployment"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-018", "chunk": "best practices", "meaning_cn": "最佳实践", "collocations": ["follow best practices", "industry best practices", "establish best practices"], "sentence": "The best teams follow best practices around AI rather than generating the most code.", "sentence_cn": "最好的团队围绕AI遵循最佳实践，而不是生成最多的代码。", "audio": "/audio/ai-coding-workflow/chunk-018.mp3", "rewrite_prompt_cn": "最好的团队围绕AI遵循最佳实践，而不是生成最多的代码。", "retelling_prompt": "What distinguishes the best teams from others in the AI era?", "tags": ["AI", "engineering"], "exam_tags": ["IELTS", "TOEFL"]},
    {"id": "ai-coding-workflow-019", "chunk": "build reliable workflows", "meaning_cn": "构建可靠的工作流", "collocations": ["build reliable workflows", "reliable workflow around AI", "workflow reliability"], "sentence": "The best teams will build reliable workflows around AI tools.", "sentence_cn": "最好的团队将围绕AI工具构建可靠的工作流。", "audio": "/audio/ai-coding-workflow/chunk-019.mp3", "rewrite_prompt_cn": "最好的团队将围绕AI工具构建可靠的工作流。", "retelling_prompt": "What kind of workflows do successful teams build?", "tags": ["workflow", "engineering"], "exam_tags": ["IELTS", "TOEFL", "Tech English"]},
    {"id": "ai-coding-workflow-020", "chunk": "faster output", "meaning_cn": "更快的产出", "collocations": ["faster output", "increase output speed", "accelerate output"], "sentence": "Faster output also creates a new problem for quality assurance.", "sentence_cn": "更快的产出也为质量保证带来了新问题。", "audio": "/audio/ai-coding-workflow/chunk-020.mp3", "rewrite_prompt_cn": "更快的产出也为质量保证带来了新问题。", "retelling_prompt": "What problems does faster output create?", "tags": ["AI", "workflow"], "exam_tags": ["IELTS", "TOEFL"]},
]

for c in new_chunks:
    if c['id'] not in existing_ids:
        data['chunks'].append(c)

with open('data/lessons/ai-coding-workflow.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f"Now has {len(data['chunks'])} chunks")
