#!/usr/bin/env python3
"""Generate 3 lesson JSON files: globalization-trade, culture-tourism, family-children"""
import json
from pathlib import Path

OUT = Path("/root/projects/english-chunk-notes/data/lessons")

def make_chunk(lesson_id, num, chunk, meaning_cn, collocations, sentence, sentence_cn,
               exam_sentence, retelling_prompt, tags, exam_tags=None):
    if exam_tags is None:
        exam_tags = ["IELTS", "TOEFL", "CET6"]
    return {
        "id": f"{lesson_id}-{num:03d}",
        "chunk": chunk,
        "meaning_cn": meaning_cn,
        "collocations": collocations,
        "sentence": sentence,
        "sentence_cn": sentence_cn,
        "exam_sentence": exam_sentence,
        "audio": f"/audio/{lesson_id}/chunk-{num:03d}.mp3",
        "rewrite_prompt_cn": sentence_cn,
        "retelling_prompt": retelling_prompt,
        "tags": tags,
        "exam_tags": exam_tags
    }

def globalization_trade():
    lid = "globalization-trade"
    c = lambda n, ch, cn, col, s, sc, es, rp, t, et=None: make_chunk(lid, n, ch, cn, col, s, sc, es, rp, t, et)
    chunks = [
        c(1, "transform the world economy", "改变世界经济格局",
          ["transform the world economy", "fundamentally transform", "transform the landscape"],
          "Globalization has transformed the world economy over the past few decades.",
          "过去几十年，全球化改变了世界经济格局。",
          "Technological innovation has transformed the global economy, creating both opportunities and challenges for developing nations.",
          "How has globalization changed the world economy?", ["globalization", "economics"]),
        c(2, "interconnected marketplace", "相互关联的市场",
          ["interconnected marketplace", "interconnected world", "interconnected global economy"],
          "The internet has created an interconnected marketplace for businesses of all sizes.",
          "互联网为各种规模的企业创造了一个相互关联的市场。",
          "In today's interconnected marketplace, a crisis in one region can quickly affect economies worldwide.",
          "What kind of marketplace has globalization created?", ["globalization", "business"]),
        c(3, "multinational corporations", "跨国公司",
          ["multinational corporations", "large multinational", "leading multinational corporations"],
          "Multinational corporations play a dominant role in the global economy.",
          "跨国公司在全球经济中发挥着主导作用。",
          "Multinational corporations are often criticized for exploiting cheap labor in developing countries while maximizing profits.",
          "What role do multinational corporations play in globalization?", ["business", "globalization"]),
        c(4, "global supply chains", "全球供应链",
          ["global supply chains", "disrupt global supply chains", "complex global supply chains"],
          "Many companies rely on global supply chains to source materials efficiently.",
          "许多公司依赖全球供应链高效地采购原材料。",
          "The pandemic exposed the fragility of global supply chains and highlighted the need for greater resilience.",
          "Why do companies use global supply chains?", ["business", "logistics"]),
        c(5, "economic interdependence", "经济相互依存",
          ["economic interdependence", "growing economic interdependence", "deep economic interdependence"],
          "Economic interdependence means that no country can isolate itself from global trends.",
          "经济相互依存意味着任何国家都无法将自己与全球趋势隔绝。",
          "Deep economic interdependence among nations makes it difficult for any single country to pursue independent trade policies.",
          "What does economic interdependence mean?", ["economics", "globalization"]),
        c(6, "free trade", "自由贸易",
          ["free trade agreement", "promote free trade", "free trade zone"],
          "Free trade allows countries to specialize in producing goods they are best at.",
          "自由贸易使各国能够专注于生产自己最擅长的商品。",
          "While free trade can stimulate economic growth, it may also widen the gap between rich and poor nations.",
          "What are the advantages of free trade?", ["trade", "economics"]),
        c(7, "lift millions out of poverty", "使数百万人摆脱贫困",
          ["lift millions out of poverty", "lift people out of poverty", "lift out of poverty"],
          "Economic reforms have lifted millions out of poverty in Southeast Asia.",
          "经济改革已使东南亚数百万人摆脱了贫困。",
          "Proponents of globalization argue that international trade has lifted millions out of poverty in developing regions.",
          "How has globalization affected poverty?", ["economics", "social"]),
        c(8, "foreign direct investment", "外国直接投资",
          ["foreign direct investment", "attract foreign direct investment", "inflows of foreign direct investment"],
          "The country is trying to attract more foreign direct investment to boost its economy.",
          "该国正试图吸引更多外国直接投资来促进经济发展。",
          "Foreign direct investment has been a key driver of economic growth in many developing countries.",
          "Why do countries seek foreign direct investment?", ["economics", "investment"]),
        c(9, "trade barriers", "贸易壁垒",
          ["remove trade barriers", "erect trade barriers", "reduce trade barriers"],
          "The government decided to remove trade barriers to encourage imports.",
          "政府决定取消贸易壁垒以鼓励进口。",
          "Although trade barriers may protect domestic industries in the short term, they often lead to higher prices for consumers.",
          "What effect do trade barriers have on trade?", ["trade", "policy"]),
        c(10, "trade deficit", "贸易逆差",
          ["widen the trade deficit", "narrow the trade deficit", "reduce the trade deficit"],
          "The country's trade deficit has widened due to increasing imports of consumer goods.",
          "由于消费品进口不断增加，该国的贸易逆差已经扩大。",
          "A persistent trade deficit can weaken a country's currency and increase its reliance on foreign borrowing.",
          "What causes a trade deficit to widen?", ["trade", "economics"]),
        c(11, "protectionism", "保护主义",
          ["rise of protectionism", "trade protectionism", "economic protectionism"],
          "Protectionism may protect local industries but often leads to trade wars.",
          "保护主义可能保护本地产业，但往往导致贸易战。",
          "The rise of protectionism in recent years has threatened to undermine decades of progress in international trade liberalization.",
          "What are the risks of protectionism?", ["trade", "policy"]),
        c(12, "economic integration", "经济一体化",
          ["economic integration", "regional economic integration", "deepen economic integration"],
          "The European Union is the most advanced example of economic integration.",
          "欧盟是经济一体化最先进的例子。",
          "Regional economic integration has accelerated cross-border investment and facilitated the movement of skilled labor.",
          "Can you give an example of economic integration?", ["economics", "policy"]),
        c(13, "international cooperation", "国际合作",
          ["international cooperation", "promote international cooperation", "strengthen international cooperation"],
          "International cooperation is essential for tackling global challenges like climate change.",
          "国际合作对于应对气候变化等全球挑战至关重要。",
          "Effective international cooperation is crucial for addressing transnational issues such as pandemics and environmental degradation.",
          "Why is international cooperation important?", ["international", "policy"]),
        c(14, "global marketplace", "全球市场",
          ["global marketplace", "compete in the global marketplace", "thrive in the global marketplace"],
          "Small businesses now have access to the global marketplace through e-commerce platforms.",
          "小企业现在通过电子商务平台可以进入全球市场。",
          "In an increasingly competitive global marketplace, innovation and adaptability are key factors for business success.",
          "How has e-commerce changed access to the global marketplace?", ["business", "e-commerce"]),
        c(15, "relocate factories", "迁移工厂",
          ["relocate factories overseas", "relocate production", "relocate manufacturing"],
          "Many companies have relocated their factories to countries with lower labor costs.",
          "许多公司已将工厂迁至劳动力成本较低的国家。",
          "When corporations relocate factories to developing countries, they often leave behind communities with high unemployment rates.",
          "Why do companies relocate their factories?", ["business", "manufacturing"]),
        c(16, "cultural exchange", "文化交流",
          ["cultural exchange", "promote cultural exchange", "international cultural exchange"],
          "Study abroad programs are an excellent way to promote cultural exchange.",
          "留学项目是促进文化交流的绝佳方式。",
          "Cultural exchange programs foster mutual understanding and help break down stereotypes between nations.",
          "How can cultural exchange benefit international relations?", ["culture", "international"], ["IELTS", "TOEFL"]),
        c(17, "lower labor costs", "更低的劳动力成本",
          ["lower labor costs", "cheap labor costs", "competitive labor costs"],
          "Lower labor costs in Asia have attracted many manufacturing companies.",
          "亚洲更低的劳动力成本吸引了许多制造企业。",
          "While lower labor costs attract foreign investment, they can also lead to the exploitation of workers in developing countries.",
          "What attracts manufacturing companies to developing countries?", ["economics", "business"]),
        c(18, "international aid", "国际援助",
          ["international aid", "provide international aid", "international aid programs"],
          "International aid has helped rebuild infrastructure after natural disasters.",
          "国际援助帮助在自然灾害后重建基础设施。",
          "Some critics argue that international aid often fails to reach those who need it most due to corruption and inefficiency.",
          "What role does international aid play in developing countries?", ["international", "social"], ["IELTS", "TOEFL"]),
        c(19, "developing nations", "发展中国家",
          ["developing nations", "developing countries", "least developed nations"],
          "Globalization has brought both benefits and challenges to developing nations.",
          "全球化给发展中国家带来了利益和挑战。",
          "Developing nations must balance the need for foreign investment with the protection of local industries and workers' rights.",
          "What are the pros and cons of globalization for developing nations?", ["economics", "globalization"]),
        c(20, "common rules", "共同规则",
          ["establish common rules", "common rules and standards", "follow common rules"],
          "Countries need to establish common rules to ensure fair competition in trade.",
          "各国需要建立共同规则以确保贸易中的公平竞争。",
          "The establishment of common rules and standards is essential for maintaining stability in the international trading system.",
          "Why are common rules important in international trade?", ["trade", "policy"]),
    ]
    return {
        "lesson_id": lid,
        "title": "Globalization and International Trade",
        "title_cn": "全球化与国际贸易",
        "category": "General English",
        "level": "B1-B2",
        "theme_tags": ["globalization", "trade", "economics", "international"],
        "exam_tags": ["IELTS", "TOEFL", "CET4", "CET6", "Postgraduate English"],
        "article": {
            "text": "Globalization has transformed the world economy over the past few decades, creating an interconnected marketplace where goods, services, and capital flow across borders with remarkable ease. Multinational corporations now operate in dozens of countries, leveraging global supply chains to reduce costs and increase efficiency. However, this economic interdependence has also sparked intense debate. Supporters argue that free trade lifts millions out of poverty by opening new markets and creating jobs in developing nations. Foreign direct investment has brought modern infrastructure and technology to regions that previously lacked access. On the other hand, critics point out that not everyone benefits equally. Manufacturing workers in developed countries often face job losses as factories relocate to areas with lower labor costs. Trade deficits in some nations have widened, fueling calls for protectionism and stricter trade barriers. Despite these challenges, economic integration continues to deepen. International cooperation through organizations like the World Trade Organization helps resolve disputes and establish common rules. The global marketplace offers enormous opportunities, but it also demands that nations adapt their policies to ensure that the benefits of trade are shared more broadly. Finding the right balance between open markets and domestic protection remains one of the most pressing economic challenges of our time.",
            "text_cn": "过去几十年，全球化改变了世界经济，创造了一个相互关联的市场，商品、服务和资本以前所未有的便利穿越国界。跨国公司如今在数十个国家运营，利用全球供应链降低成本、提高效率。然而，这种经济相互依存也引发了激烈的争论。支持者认为，自由贸易通过开辟新市场和在发展中国家创造就业，使数百万人摆脱贫困。外国直接投资为以前无法获得现代基础设施和技术的地区带来了这些资源。另一方面，批评者指出并非所有人都能平等受益。发达国家的制造业工人经常面临失业，因为工厂迁往劳动力成本更低的地区。一些国家的贸易逆差不断扩大，加剧了对保护主义和更严格贸易壁垒的呼声。尽管面临这些挑战，经济一体化仍在不断深化。通过世界贸易组织等机构的国际合作有助于解决争端并制定共同规则。全球市场提供了巨大的机遇，但也要求各国调整政策，确保贸易利益得到更广泛的分享。在开放市场和国内保护之间找到适当的平衡，仍然是我们时代最紧迫的经济挑战之一。",
            "audio": "/audio/globalization-trade/article.mp3"
        },
        "model_paragraph": {
            "text": "Globalization has created an interconnected world economy where free trade and foreign investment offer tremendous opportunities, but the benefits are not always distributed equally across nations and social groups.",
            "text_cn": "全球化创造了一个相互关联的世界经济，自由贸易和外国投资提供了巨大的机遇，但这些利益并非总是在各国和社会群体之间平等分配。"
        },
        "chunks": chunks
    }

def culture_tourism():
    lid = "culture-tourism"
    c = lambda n, ch, cn, col, s, sc, es, rp, t, et=None: make_chunk(lid, n, ch, cn, col, s, sc, es, rp, t, et)
    chunks = [
        c(1, "cultural heritage", "文化遗产",
          ["preserve cultural heritage", "rich cultural heritage", "protect cultural heritage"],
          "Preserving cultural heritage is essential for maintaining a nation's identity.",
          "保护文化遗产对于维护一个国家的认同至关重要。",
          "Governments should invest in preserving cultural heritage sites before they are lost to urban development.",
          "Why is cultural heritage important?", ["culture", "heritage"]),
        c(2, "cultural diversity", "文化多样性",
          ["promote cultural diversity", "respect cultural diversity", "celebrate cultural diversity"],
          "Cultural diversity makes our world more interesting and vibrant.",
          "文化多样性使我们的世界更加有趣和充满活力。",
          "Cultural diversity enriches societies by bringing together different perspectives, traditions, and forms of artistic expression.",
          "Why should we value cultural diversity?", ["culture", "society"]),
        c(3, "tourism industry", "旅游业",
          ["boost the tourism industry", "tourism industry growth", "develop the tourism industry"],
          "The tourism industry is a major source of employment in many coastal cities.",
          "旅游业是许多沿海城市的主要就业来源。",
          "The rapid expansion of the tourism industry has created millions of jobs but also placed pressure on local infrastructure.",
          "What role does the tourism industry play in employment?", ["tourism", "business"]),
        c(4, "cultural assimilation", "文化同化",
          ["cultural assimilation", "resist cultural assimilation", "process of cultural assimilation"],
          "Cultural assimilation can cause traditional practices to disappear over time.",
          "文化同化可能导致传统习俗随时间消失。",
          "While cultural assimilation can promote social cohesion, it often comes at the cost of losing unique traditions and languages.",
          "What are the negative effects of cultural assimilation?", ["culture", "society"], ["IELTS", "TOEFL"]),
        c(5, "cross-cultural communication", "跨文化交流",
          ["cross-cultural communication", "improve cross-cultural communication", "effective cross-cultural communication"],
          "Cross-cultural communication skills are valuable in today's globalized workplace.",
          "跨文化交流技能在当今全球化的职场中很有价值。",
          "Effective cross-cultural communication reduces misunderstandings and builds stronger relationships between people from different backgrounds.",
          "Why are cross-cultural communication skills important?", ["culture", "communication"]),
        c(6, "cultural identity", "文化认同",
          ["preserve cultural identity", "strengthen cultural identity", "lose cultural identity"],
          "Many communities are working hard to preserve their cultural identity.",
          "许多社区正在努力保护其文化认同。",
          "Globalization threatens cultural identity by promoting a homogenized consumer culture that erodes local traditions.",
          "What threatens cultural identity?", ["culture", "identity"]),
        c(7, "traditional customs", "传统习俗",
          ["traditional customs and practices", "preserve traditional customs", "observe traditional customs"],
          "Traditional customs are an important part of a community's cultural heritage.",
          "传统习俗是社区文化遗产的重要组成部分。",
          "Efforts to document and preserve traditional customs are crucial before they fade from living memory.",
          "Why should we preserve traditional customs?", ["culture", "tradition"], ["IELTS", "TOEFL"]),
        c(8, "tourism revenue", "旅游收入",
          ["generate tourism revenue", "tourism revenue growth", "increase tourism revenue"],
          "Tourism revenue helps fund public services in many small island nations.",
          "旅游收入帮助许多小岛国资助公共服务。",
          "While tourism revenue can significantly boost local economies, over-reliance on this income source makes destinations vulnerable to global disruptions.",
          "How does tourism revenue benefit local communities?", ["tourism", "economics"]),
        c(9, "cultural preservation", "文化保护",
          ["cultural preservation efforts", "prioritize cultural preservation", "support cultural preservation"],
          "Cultural preservation requires both government funding and community participation.",
          "文化保护需要政府资金和社区参与。",
          "Cultural preservation should be a priority for governments, as the loss of heritage is irreversible.",
          "What is needed for effective cultural preservation?", ["culture", "heritage"], ["IELTS", "TOEFL"]),
        c(10, "UNESCO World Heritage", "联合国教科文组织世界遗产",
          ["UNESCO World Heritage site", "UNESCO World Heritage list", "UNESCO World Heritage status"],
          "The Great Wall is a famous UNESCO World Heritage site in China.",
          "长城是中国著名的联合国教科文组织世界遗产。",
          "UNESCO World Heritage designation brings international attention and funding, which can support long-term conservation efforts.",
          "What is the significance of UNESCO World Heritage status?", ["heritage", "travel"], ["IELTS", "TOEFL"]),
        c(11, "sustainable tourism", "可持续旅游",
          ["promote sustainable tourism", "sustainable tourism practices", "develop sustainable tourism"],
          "Sustainable tourism aims to minimize environmental impact while benefiting local communities.",
          "可持续旅游旨在最小化环境影响，同时造福当地社区。",
          "Sustainable tourism practices are essential to ensure that future generations can enjoy the world's natural and cultural treasures.",
          "What are the goals of sustainable tourism?", ["tourism", "environment"]),
        c(12, "homestay programs", "民宿项目",
          ["homestay programs", "participate in homestay programs", "offer homestay experiences"],
          "Homestay programs allow travelers to experience local culture firsthand.",
          "民宿项目让旅行者亲身体验当地文化。",
          "Homestay programs provide authentic cultural experiences while distributing tourism income directly to host families.",
          "What are the benefits of homestay programs?", ["tourism", "culture"], ["IELTS", "TOEFL"]),
        c(13, "cultural exchange programs", "文化交流项目",
          ["cultural exchange programs", "participate in cultural exchange programs", "organize cultural exchange programs"],
          "Cultural exchange programs help students develop a global perspective.",
          "文化交流项目帮助学生培养全球视野。",
          "Cultural exchange programs not only broaden individual horizons but also strengthen diplomatic ties between nations.",
          "How do cultural exchange programs benefit students?", ["culture", "education"]),
        c(14, "mass tourism", "大众旅游",
          ["mass tourism", "negative effects of mass tourism", "manage mass tourism"],
          "Mass tourism can cause environmental damage to popular destinations.",
          "大众旅游可能对热门目的地造成环境破坏。",
          "The negative effects of mass tourism include overcrowding, pollution, and the degradation of local cultural sites.",
          "What problems does mass tourism cause?", ["tourism", "environment"]),
        c(15, "commercialization of culture", "文化商业化",
          ["commercialization of culture", "prevent commercialization", "excessive commercialization"],
          "The commercialization of cultural festivals has changed their original meaning.",
          "文化节的商业化改变了它们原有的意义。",
          "The excessive commercialization of traditional festivals risks turning meaningful cultural celebrations into superficial tourist attractions.",
          "How does commercialization affect cultural traditions?", ["culture", "tourism"]),
        c(16, "mutual understanding", "相互理解",
          ["foster mutual understanding", "promote mutual understanding", "build mutual understanding"],
          "Travel can foster mutual understanding between people from different backgrounds.",
          "旅行可以促进不同背景人们之间的相互理解。",
          "Promoting mutual understanding between cultures is one of the most valuable outcomes of international educational programs.",
          "How does travel promote mutual understanding?", ["culture", "society"]),
        c(17, "authentic cultural experiences", "真实的文化体验",
          ["authentic cultural experiences", "provide authentic experiences", "seek authentic experiences"],
          "Many tourists today seek authentic cultural experiences rather than standard tourist attractions.",
          "如今许多游客寻求真实的文化体验，而非标准的旅游景点。",
          "Providing authentic cultural experiences requires careful planning to avoid turning local traditions into mere performances.",
          "Why do tourists seek authentic cultural experiences?", ["tourism", "culture"]),
        c(18, "community development", "社区发展",
          ["support community development", "promote community development", "community development projects"],
          "Tourism can play a significant role in supporting community development in rural areas.",
          "旅游在支持农村社区发展方面可以发挥重要作用。",
          "When managed responsibly, tourism can contribute to community development by creating jobs and funding local infrastructure.",
          "How can tourism support community development?", ["tourism", "society"]),
        c(19, "passed down through generations", "代代相传",
          ["passed down through generations", "traditions passed down", "knowledge passed down"],
          "Many traditional crafts have been passed down through generations of artisans.",
          "许多传统工艺已经在工匠中代代相传。",
          "Traditions passed down through generations represent an irreplaceable cultural legacy that modernization should not erase.",
          "Why is it important to preserve traditions passed down through generations?", ["culture", "tradition"]),
        c(20, "conservation efforts", "保护努力",
          ["conservation efforts", "support conservation efforts", "fund conservation efforts"],
          "Conservation efforts have saved several endangered heritage sites from destruction.",
          "保护努力已拯救了几个濒危遗产地免遭破坏。",
          "Increased conservation efforts are urgently needed to protect cultural and natural heritage sites that face threats from climate change and urbanization.",
          "What do conservation efforts aim to protect?", ["heritage", "environment"]),
    ]
    return {
        "lesson_id": lid,
        "title": "Culture, Heritage and Tourism",
        "title_cn": "文化、遗产与旅游",
        "category": "General English",
        "level": "B1-B2",
        "theme_tags": ["culture", "tourism", "heritage", "travel"],
        "exam_tags": ["IELTS", "TOEFL", "CET4", "CET6", "Postgraduate English"],
        "article": {
            "text": "Tourism has become one of the largest industries in the world, generating billions of dollars in revenue each year. For many countries, cultural heritage is the primary attraction that draws international visitors. From ancient temples in Southeast Asia to medieval castles in Europe, these sites offer travelers a chance to connect with history and experience traditions that have been passed down through generations. However, the rapid growth of the tourism industry has raised serious concerns about cultural preservation. Popular destinations often struggle to balance economic benefits with the need to protect their cultural identity. Mass tourism can lead to the commercialization of traditional customs, where authentic cultural practices are simplified or altered to suit tourist expectations. In some cases, cultural assimilation occurs as local communities gradually adopt foreign lifestyles in response to constant interaction with visitors. On the positive side, tourism revenue can fund conservation efforts and support community development. UNESCO World Heritage sites, for instance, often receive significant funding to maintain their historical significance. Sustainable tourism initiatives, including homestay programs and cultural exchange programs, allow visitors to experience local life in a more respectful and authentic way. Cross-cultural communication between tourists and hosts can foster mutual understanding and appreciation. The challenge for the future is ensuring that tourism grows in a way that celebrates cultural diversity rather than diminishing it.",
            "text_cn": "旅游业已成为世界上最大的产业之一，每年产生数十亿美元的财政收入。对于许多国家来说，文化遗产是吸引国际游客的主要资源。从东南亚的古老寺庙到欧洲的中世纪城堡，这些遗址让旅行者有机会与历史建立联系，体验代代相传的传统。然而，旅游业的快速增长引发了关于文化保护的严重担忧。热门目的地往往难以在经济利益和保护文化认同的需要之间取得平衡。大众旅游可能导致传统习俗的商业化，真正的文化实践被简化或改变以迎合游客的期望。在某些情况下，由于当地社区在与游客不断互动中逐渐采纳外国生活方式，文化同化现象随之发生。积极的一面是，旅游收入可以资助保护工作并支持社区发展。例如，联合国教科文组织世界遗产地通常获得大量资金来维护其历史意义。可持续旅游举措，包括民宿项目和文化交流项目，使游客能够以更尊重和真实的方式体验当地生活。游客与东道主之间的跨文化交流可以增进相互理解和欣赏。未来的挑战是确保旅游业以庆祝而非削弱文化多样性的方式发展。",
            "audio": "/audio/culture-tourism/article.mp3"
        },
        "model_paragraph": {
            "text": "While tourism generates significant revenue and funds cultural preservation, it also poses risks to cultural identity through commercialization and assimilation, making sustainable tourism practices essential.",
            "text_cn": "虽然旅游业产生了可观的收入并资助了文化保护，但它也通过商业化和同化对文化认同构成了威胁，因此可持续旅游实践至关重要。"
        },
        "chunks": chunks
    }

def family_children():
    lid = "family-children"
    c = lambda n, ch, cn, col, s, sc, es, rp, t, et=None: make_chunk(lid, n, ch, cn, col, s, sc, es, rp, t, et)
    chunks = [
        c(1, "nuclear family", "核心家庭",
          ["nuclear family", "traditional nuclear family", "typical nuclear family"],
          "The nuclear family has become the most common household structure in urban areas.",
          "核心家庭已成为城市地区最常见的家庭结构。",
          "The shift from extended to nuclear family structures has weakened traditional support systems for child-rearing in many societies.",
          "What is a nuclear family?", ["family", "society"]),
        c(2, "extended family", "大家庭",
          ["extended family", "live with extended family", "extended family support"],
          "In many cultures, the extended family plays a vital role in raising children.",
          "在许多文化中，大家庭在抚养孩子方面发挥着至关重要的作用。",
          "Children who grow up in extended family households often develop stronger social skills and a greater sense of belonging.",
          "What role does the extended family play?", ["family", "culture"]),
        c(3, "child development", "儿童发展",
          ["child development", "early child development", "promote child development"],
          "Good nutrition and a loving environment are essential for healthy child development.",
          "良好的营养和充满爱的环境对儿童健康发展至关重要。",
          "Research has shown that early childhood experiences have a profound impact on long-term cognitive development and emotional well-being.",
          "What factors are important for child development?", ["family", "education"]),
        c(4, "parenting styles", "育儿方式",
          ["parenting styles", "different parenting styles", "parenting styles influence"],
          "Parenting styles vary significantly across different cultures and generations.",
          "育儿方式在不同的文化和世代之间差异很大。",
          "Studies suggest that authoritative parenting styles, which balance warmth with clear boundaries, tend to produce the best outcomes for children.",
          "How do parenting styles differ?", ["family", "education"]),
        c(5, "work-life balance", "工作与生活平衡",
          ["achieve work-life balance", "improve work-life balance", "maintain work-life balance"],
          "Many parents struggle to achieve a healthy work-life balance.",
          "许多父母努力实现健康的工作与生活平衡。",
          "Employers who offer flexible working arrangements help parents achieve better work-life balance, which ultimately benefits both families and businesses.",
          "Why is work-life balance important for parents?", ["work", "family"]),
        c(6, "single-parent families", "单亲家庭",
          ["single-parent families", "children from single-parent families", "rise in single-parent families"],
          "The number of single-parent families has increased significantly in recent decades.",
          "近几十年来单亲家庭的数量显著增加。",
          "Children from single-parent families may face financial challenges, but many thrive with strong community support and engaged parenting.",
          "What challenges do single-parent families face?", ["family", "society"]),
        c(7, "gender roles", "性别角色",
          ["traditional gender roles", "challenge gender roles", "gender roles in the family"],
          "Traditional gender roles are slowly changing in many modern societies.",
          "传统性别角色在许多现代社会中正在缓慢变化。",
          "Breaking down rigid gender roles in the family allows both parents to contribute equally to household responsibilities and career development.",
          "How are gender roles changing in families?", ["family", "society"]),
        c(8, "family values", "家庭价值观",
          ["family values", "traditional family values", "instill family values"],
          "Family values are passed from parents to children through daily interactions.",
          "家庭价值观通过日常互动从父母传递给孩子。",
          "While family values vary across cultures, shared principles such as respect, honesty, and compassion are universally important.",
          "How are family values transmitted to children?", ["family", "values"]),
        c(9, "child welfare", "儿童福利",
          ["child welfare", "child welfare system", "protect child welfare"],
          "Governments have a responsibility to protect child welfare through legislation and social programs.",
          "政府有责任通过立法和社会项目保护儿童福利。",
          "Investing in child welfare programs yields long-term benefits for society by reducing crime rates and improving educational outcomes.",
          "Why is child welfare important for society?", ["family", "social policy"]),
        c(10, "domestic responsibilities", "家庭责任",
          ["share domestic responsibilities", "domestic responsibilities", "household domestic responsibilities"],
          "Sharing domestic responsibilities fairly is key to a harmonious family life.",
          "公平分担家庭责任是和谐家庭生活的关键。",
          "When both partners share domestic responsibilities equally, it reduces stress and promotes healthier relationships within the family.",
          "Why is sharing domestic responsibilities important?", ["family", "daily life"]),
        c(11, "early childhood education", "幼儿教育",
          ["early childhood education", "invest in early childhood education", "access to early childhood education"],
          "Early childhood education gives children a strong foundation for future learning.",
          "幼儿教育为孩子的未来学习打下坚实基础。",
          "Access to quality early childhood education can help narrow the achievement gap between children from different socioeconomic backgrounds.",
          "Why is early childhood education important?", ["education", "family"]),
        c(12, "family bonds", "家庭纽带",
          ["strengthen family bonds", "close family bonds", "maintain family bonds"],
          "Spending quality time together helps strengthen family bonds.",
          "一起度过高质量的时间有助于加强家庭纽带。",
          "Strong family bonds provide emotional support that helps individuals cope with stress and adversity throughout their lives.",
          "How can families strengthen their bonds?", ["family", "relationships"]),
        c(13, "upbringing", "成长教养",
          ["upbringing", "good upbringing", "responsible upbringing"],
          "A child's upbringing has a lasting impact on their character and behavior.",
          "孩子的成长教养对其性格和行为有持久的影响。",
          "Research indicates that a nurturing upbringing during the early years is more influential than genetic factors in shaping personality.",
          "How does upbringing affect a child's future?", ["family", "education"]),
        c(14, "child-rearing", "抚养孩子",
          ["child-rearing practices", "child-rearing responsibilities", "approach to child-rearing"],
          "Child-rearing practices differ greatly from one culture to another.",
          "抚养孩子的方式在不同文化之间差异很大。",
          "Modern child-rearing approaches increasingly emphasize emotional intelligence and creativity over strict discipline and obedience.",
          "How do child-rearing practices vary across cultures?", ["family", "education"]),
        c(15, "quality time", "高质量时光",
          ["spend quality time", "quality time with family", "quality time together"],
          "Parents should try to spend quality time with their children every day.",
          "父母应该尽量每天都和孩子度过高质量时光。",
          "Spending quality time with family members has been linked to improved mental health and stronger interpersonal relationships.",
          "Why is quality time important for families?", ["family", "daily life"], ["IELTS", "TOEFL"]),
        c(16, "role model", "榜样",
          ["serve as a role model", "positive role model", "be a role model for"],
          "Parents naturally serve as the first role models for their children.",
          "父母自然成为孩子的第一个榜样。",
          "Children who grow up with positive role models are more likely to develop confidence and a strong sense of moral responsibility.",
          "Why are parents important role models?", ["family", "education"]),
        c(17, "emotional support", "情感支持",
          ["provide emotional support", "emotional support from family", "lack of emotional support"],
          "A loving family provides essential emotional support during difficult times.",
          "充满爱的家庭在困难时期提供必要的情感支持。",
          "Children who receive consistent emotional support from their families are better equipped to handle challenges in adulthood.",
          "How does emotional support from family help children?", ["family", "psychology"]),
        c(18, "generational gap", "代沟",
          ["generational gap", "bridge the generational gap", "widen the generational gap"],
          "The generational gap between parents and teenagers can sometimes lead to conflicts.",
          "父母与青少年之间的代沟有时会导致冲突。",
          "Open communication and mutual respect are effective ways to bridge the generational gap within families.",
          "What causes the generational gap?", ["family", "society"]),
        c(19, "household", "家庭；户",
          ["single-person household", "multi-generational household", "household income"],
          "The structure of the average household has changed dramatically over the past century.",
          "过去一个世纪，普通家庭的结构发生了巨大变化。",
          "Changes in household composition, including the rise of single-person and multi-generational households, reflect broader social and economic shifts.",
          "How have household structures changed?", ["family", "society"]),
        c(20, "nurturing environment", "培育环境",
          ["nurturing environment", "provide a nurturing environment", "create a nurturing environment"],
          "Children thrive when they grow up in a nurturing environment.",
          "孩子在培育环境中成长时能够茁壮发展。",
          "Creating a nurturing environment at home is one of the most effective ways to support a child's cognitive and emotional development.",
          "What does a nurturing environment mean for children?", ["family", "education"]),
    ]
    return {
        "lesson_id": lid,
        "title": "Family, Children and Upbringing",
        "title_cn": "家庭、儿童与成长",
        "category": "General English",
        "level": "B1-B2",
        "theme_tags": ["family", "children", "upbringing", "society"],
        "exam_tags": ["IELTS", "TOEFL", "CET4", "CET6", "Postgraduate English"],
        "article": {
            "text": "The concept of family has evolved significantly in modern society. While the nuclear family remains common in many Western countries, the extended family continues to be the norm in various parts of Asia, Africa, and Latin America. Each family structure offers unique advantages for child development and upbringing. In nuclear families, parents often bear the full responsibility for domestic responsibilities and child-rearing, which can make work-life balance a significant challenge. The rise of single-parent families has added another layer of complexity, as many single parents must juggle earning a living with providing emotional support and guidance for their children. Parenting styles also vary widely. Some families emphasize strict discipline and academic achievement, while others prioritize creativity and independence. Research increasingly suggests that a nurturing environment, where children feel loved and supported, is more important than any specific parenting approach. Family values, including respect, honesty, and compassion, are typically instilled through daily interactions and the examples set by parents who serve as role models. The generational gap can create tension, especially when children adopt values that differ from those of their parents. However, spending quality time together can strengthen family bonds and bridge these differences. Access to early childhood education has become a priority for many families, as it provides children with a strong foundation for future learning. Ultimately, child welfare depends on the collective effort of families, communities, and governments working together to create the best possible conditions for the next generation.",
            "text_cn": "家庭的概念在现代社会中发生了显著变化。虽然核心家庭在许多西方国家仍然普遍，但大家庭在亚洲、非洲和拉丁美洲的许多地区仍然是常态。每种家庭结构都为儿童发展和成长提供了独特的优势。在核心家庭中，父母通常承担家庭责任和抚养孩子的全部责任，这可能使工作与生活平衡成为一个重大挑战。单亲家庭的兴起增加了另一层复杂性，因为许多单亲父母必须
